### ISSUE TITLE
arrow shown in mobile no. and email subject under contact

### ISSUE THREAD

**Issue by gamandeepsingh** [marioslazaro/website#2]
when u hover over mobile no. or email subject  input box  under Contact Me section u will see a side arrow which is not looking good . So pls assign me to correct it under hactoberfest label

**Comment by marioslazaro** [comment]
This repo is already under the tag hactoberfest, you just need  to fork this repository and submit your pull request.

**Comment by gamandeepsingh** [comment]
pls tag the issue also....... it's not showing on hactoberfest webpage
